FROM python:3.10-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance

RUN pip install \
    dagster==1.4.15 \
    dagster-postgres==0.20.15 \
    pandas==2.1.0 \
    geopandas==0.14.0 \
    matplotlib==3.8.0 \
    seaborn==0.12.2 \
    pyarrow==13.0.0 \
    dagster-aws==0.20.15 \
    httpx==0.24.1 \
    tenacity==8.2.3 \
    xmltodict==0.13.0

ARG DAGSTER_HOME

ARG DAGSTER_MODULE_NAME

# Add repository code
RUN mkdir -p ${DAGSTER_HOME}

# Copy your code and workspace and dagster instance YAML to /opt/dagster/dagster_home/
COPY dagster.yaml workspace.yaml ${DAGSTER_HOME}

# Copy your code and workspace and dagster instance YAML to /opt/dagster/dagster_home/
COPY ./${DAGSTER_MODULE_NAME}/ ${DAGSTER_HOME}${DAGSTER_MODULE_NAME}

# Copy your code and workspace and dagster instance YAML to /opt/dagster/dagster_home/
COPY ./${DAGSTER_MODULE_NAME}_tests/ ${DAGSTER_HOME}${DAGSTER_MODULE_NAME}_tests

# Run dagster gRPC server on port 4000
EXPOSE 4000

WORKDIR ${DAGSTER_HOME}
