FROM python:3.10-slim

RUN pip install \
    dagster==1.4.15 \
    dagster-postgres==0.20.15 \
    dagster-webserver==1.4.15 \
    pandas==2.1.0 \
    dagster-aws==0.20.15

ARG DAGSTER_HOME

ARG DAGSTER_MODULE_NAME

RUN mkdir -p ${DAGSTER_HOME}

# Copy dagster instance YAML to /opt/dagster/dagster_home/
COPY dagster.yaml workspace.yaml ${DAGSTER_HOME}

WORKDIR ${DAGSTER_HOME}
